# Generated by Django 3.2.8 on 2021-11-30 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_purchase_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='day',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='inventory.revenueday'),
        ),
    ]
